<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Additional message' => 'Дополнительное сообщение',
    'An email was sent to your email address specified in Whois. To start the transfer, click on the link in the email.' => 'Письмо отправлено на емейл указанный в WHOIS. Чтобы начать трансфер нажмите на ссылку в письме.',
    'Bulk domain transfer' => 'Массовый трансфер',
    'Domain transfer' => 'Трансфер домена',
    'Transfer domain' => 'Трансфер домена',
    'Transfer' => 'Трансфер',
    'Example' => 'Пример',
    'For separation of the domain and code use a space, a comma or a semicolon.' => 'Для отделения домена от пароя используйте пробел, запятую или точку с запятой.',
    'Remove WHOIS protection from the current registrar.' => 'Отключите защиту WHOIS у текущего регистратора.',
    'Return to transfer form' => 'Вернуться на форму трансфера',
    'Starting the transfer procedure for the following domains' => 'Начинаем процедуру трансфера для следующих доменов',
    'WHOIS' => 'WHOIS',
    'each pair (domain + code) should be written with a new line' => 'каждая пара (домен + пароль) должна быть написана с новой строки',
    'or' => 'или',
    'Add to cart' => 'Добавить в корзину',
    'Adding' => 'Добавление',
    'Adult' => 'Для взрослых',
    'All' => 'Все',
    'Audio&Music' => 'Музыка и Аудио',
    'Available' => 'Доступные',
    'Categories' => 'Категории',
    'Domain check' => 'Поиск домена',
    'Domain is not available' => 'Домен не доступен',
    'Domain name' => 'Имя домена',
    'GEO' => 'Географические',
    'General' => 'Основные',
    'Home&Gifts' => 'Дом и подарки',
    'In cart' => 'В корзине',
    'Internet' => 'Интернет',
    'Nature' => 'Природа',
    'Popular Domains' => 'Популярные домены',
    'Promotion' => 'Акционные',
    'Search' => 'Поиск',
    'Society' => 'Общество',
    'Special' => 'Специальные',
    'Sport' => 'Спорт',
    'Status' => 'Статус',
    'There are no available domain zones' => 'Нет свободных доменных зон',
    'Unavailable' => 'Недоступны',
    'year' => 'год',

    'Domain transfer was canceled' => 'Трансфер домена был отменён',
    'Domain transfer was rejected' => 'Трансфер домена был отклонён',
    'Domain transfer was approved' => 'Трансфер домена был подтверждён',
    'FOA was sent' => 'FOA была отправлена',
];
