<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add to cart' => 'Добавить в корзину',
    'Special' => 'Спациальные',
    'Adding' => 'Добавление',
    'Adult' => 'Для взрослых',
    'All' => 'Все',
    'Audio&Music' => 'Музыка и Аудио',
    'Available' => 'Доступные',
    'Categories' => 'Категории',
    'Domain check' => 'Поиск домена',
    'Domain is not available' => 'Домен не доступен',
    'Domain name' => 'Имя домена',
    'GEO' => 'Географические',
    'General' => 'Основные',
    'Home&Gifts' => 'Дом и подарки',
    'In cart' => 'В корзине',
    'Internet' => 'Интернет',
    'Nature' => 'Природа',
    'Popular Domains' => 'Популярные домены',
    'Promotion' => 'Акционные',
    'Search' => 'Поиск',
    'Society' => 'Общество',
    'Sport' => 'Спорт',
    'Status' => 'Статус',
    'There are no available domain zones' => 'Нет свободных доменных зон',
    'Unavailable' => 'Недоступны',
    'WHOIS' => '',
    'year' => 'год',
];
